[phases.setup]
nixPkgs = ["nodejs_22", "pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = [
  "pnpm run build",
  "pnpm prisma generate"
]

[phases.deploy]
cmds = ["pnpm prisma migrate deploy"]

[start]
cmd = "pnpm run start"
